a=int(input("Enter a first number":))
b=int(input("Enter a second number"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("MOdulus:",a%b)
print("Floor Division:",a||b)
print("Power:",a**b)